name: Windows-RDP-Pinggy

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable Windows RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Custom RDP Password
      run: |
        net user runneradmin TomarJi99!

    - name: Start Pinggy TCP Tunnel
      run: |
        # Background job with pseudo-terminal allocation (-tt)
        $job = Start-Job -ScriptBlock {
            ssh -tt -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -p 443 -R0:localhost:3389 tcp@free.pinggy.io
        }
        
        Start-Sleep -Seconds 12
        
        Write-Host "========================================"
        Receive-Job -Job $job -Keep
        Write-Host "========================================"
        Write-Host "USERNAME: runneradmin"
        Write-Host "PASSWORD: TomarJi99!"
        Write-Host "========================================"

    - name: Keep Alive Loop
      run: |
        $i = 1
        while ($i -le 360) {
            Start-Sleep -Seconds 60
            $i++
        }
        
